apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
spec:
  workspaces:
    - name: source-code
  params:
    - name: url
      type: string
    - name: revision
      type: string
      default: "main"
  steps:
    - name: clone
      image: alpine/git
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
      script: |
        #!/bin/sh
        set -e
        echo "Workspace path: $(workspaces.source-code.path)"
        find $(workspaces.source-code.path) -mindepth 1 -delete
        REPO_PATH=$(echo "$(params.url)" | sed 's|https://github.com/||')
        echo "Cloning repo https://$GIT_USERNAME:$GIT_TOKEN@github.com/$REPO_PATH --branch $(params.revision)"
        git clone https://$GIT_USERNAME:$GIT_TOKEN@github.com/$REPO_PATH --branch $(params.revision) $(workspaces.source-code.path)
        ls -al $(workspaces.source-code.path)
      env:
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: github-secret
              key: username
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-secret
              key: password
