apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: cicd-pipeline
spec:
  params:
    - name: repository-url
      type: string
    - name: revision
      type: string
    - name: container-image
      type: string
  workspaces:
    - name: shared-workspace      # Pipeline 워크스페이스 이름
  tasks:
    - name: clone
      taskRef:
        name: git-clone            # 보통 clone 작업에는 git-clone Task를 씁니다
      params:
        - name: url
          value: $(params.repository-url)
        - name: revision         
          value: $(params.revision)
      workspaces:
        - name: source-code         # Task 내부에서 사용할 워크스페이스 별칭
          workspace: shared-workspace  # Pipeline 워크스페이스 이름과 매칭
    - name: build-push
      runAfter: [clone]
      taskRef:
        name: build-and-push
      params:
        - name: container-image
          value: $(params.container-image)
      workspaces:
        - name: source-code         # build-and-push Task 내 워크스페이스 별칭 (같이 쓰는 공간)
          workspace: shared-workspace
